# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ed021aaf7092348ff9c616e2c84f28677f8cfe0f48b29a1db4fcfdd1a868818d7a294f149ee533a74f41f824d615ab44204348d1877165cd2301f92dc95bb69

test:
  secret_key_base: f029447eb7cd68d9fdcf71bc7f5ecd4ead0c80d3e058880d120e5fe1b63fbcb048f0a2983d1c069dfb1e8307792b0ab6ecf67a84dd4fc52c4e47def6088787de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
